-- SQL script to fix broken links
-- Generated by analyze_full_graph.py

BEGIN TRANSACTION;


UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/integrity-ethics/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/integrity-ethics/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/systems-thinking/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/systems-thinking/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/decision-making/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/decision-making/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/story-portfolio/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/story-portfolio/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/interactive/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/interactive/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/star-framework/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/star-framework/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/hard-earned-wisdom/crisis-leadership-reality', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/hard-earned-wisdom/crisis-leadership-reality';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/hard-earned-wisdom/human-cost-leadership', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/hard-earned-wisdom/human-cost-leadership';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/hard-earned-wisdom/impossible-decisions', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/hard-earned-wisdom/impossible-decisions';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/hard-earned-wisdom/managing-up-dark-art', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/hard-earned-wisdom/managing-up-dark-art';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/hard-earned-wisdom/organizational-politics-mastery', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/hard-earned-wisdom/organizational-politics-mastery';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/hard-earned-wisdom/performance-management-reality', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/hard-earned-wisdom/performance-management-reality';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/systems-thinking/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/systems-thinking/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/integrity-ethics/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/integrity-ethics/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/operations/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/operations/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/decision-making/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/decision-making/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/strategy/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/strategy/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/operations/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/operations/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/people-management/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/people-management/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/business-acumen/business-metrics', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/business-acumen/business-metrics';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/business-acumen/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/business-acumen/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/organizational-design/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/organizational-design/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/people-management/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/people-management/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/principle-hooks/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/principle-hooks/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/star-framework/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/star-framework/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/story-portfolio/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/story-portfolio/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/tools/principle-hooks/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/tools/principle-hooks/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/integrity-ethics/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/integrity-ethics/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/systems-thinking/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/systems-thinking/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/risk-governance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/risk-governance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/strategy/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/strategy/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/organizational-design/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/organizational-design/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/people-management/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/people-management/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/behavioral/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/behavioral/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/system-org-design/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/system-org-design/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/decision-making/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/decision-making/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/integrity-ethics/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/integrity-ethics/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/operations/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/operations/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/risk-governance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/risk-governance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/organizational-design/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/organizational-design/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/people-management/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/people-management/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/behavioral/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/behavioral/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/culture-values/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/culture-values/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/decision-making/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/decision-making/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/systems-thinking/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/systems-thinking/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/finance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/finance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/risk-governance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/risk-governance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/business-acumen/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/business-acumen/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/people-management/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/people-management/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/behavioral/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/behavioral/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/culture-values/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/culture-values/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/decision-making/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/decision-making/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/risk-governance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/risk-governance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/strategy/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/strategy/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/business-acumen/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/business-acumen/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/organizational-design/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/organizational-design/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/system-org-design/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/system-org-design/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/integrity-ethics/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/integrity-ethics/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/systems-thinking/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/systems-thinking/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/finance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/finance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/operations/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/operations/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/business-acumen/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/business-acumen/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/people-management/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/people-management/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-3-applications/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-3-applications/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/behavioral/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/behavioral/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-4-interview-execution/technical-leadership/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-4-interview-execution/technical-leadership/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/decision-making/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/decision-making/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/human-behavior/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/human-behavior/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/integrity-ethics/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/integrity-ethics/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/systems-thinking/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/systems-thinking/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-1-first-principles/value-creation/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-1-first-principles/value-creation/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/finance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/finance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/risk-governance/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/risk-governance/index';

UPDATE links 
SET dst_page = 'interview-prep/engineering-leadership/level-2-core-business/strategy/index', is_valid = 1
WHERE dst_page = 'interview-prep/engineering-leadership/engineering-leadership/level-2-core-business/strategy/index';

COMMIT;
