# Microservices Orchestration with Service Mesh
# Indian E-commerce Platform के लिए Istio-based service mesh
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: indian-ecommerce-mesh
  namespace: istio-system
spec:
  values:
    global:
      meshID: indian-ecommerce
      network: mumbai-network
      # Indian region configuration
      region: ap-south-1
      zone: mumbai-1a
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
            value: true
          - name: PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY
            value: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi" 
            cpu: "1000m"
---
# Virtual Service for Indian Payment Flow
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: payment-routing
  namespace: payment-production
spec:
  hosts:
    - payment-api.ecommerce.com
  http:
    # Route based on payment method (Indian preferences)
    - match:
        - headers:
            payment-method:
              exact: "upi"
      route:
        - destination:
            host: upi-payment-service
            port:
              number: 8080
          weight: 100
      fault:
        delay:
          percentage:
            value: 0.1
          fixedDelay: 100ms
    
    - match:
        - headers:
            payment-method:
              exact: "netbanking"
      route:
        - destination:
            host: netbanking-service
            port:
              number: 8080
          weight: 100
    
    # Default route for cards and wallets
    - route:
        - destination:
            host: payment-gateway-service
            port:
              number: 8080
          weight: 100