apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    env: production
    istio-injection: enabled

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    requests.cpu: "1000"
    requests.memory: 2000Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "5"
