# Flux GitOps Configuration for Payment Systems
# Razorpay, PhonePe जैसे Indian payment gateways के लिए
apiVersion: v1
kind: Namespace
metadata:
  name: flux-payment-system
  labels:
    name: flux-payment-system
    compliance: rbi-approved
    criticality: high

---
# GitRepository for Payment Service
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: payment-gateway-repo
  namespace: flux-payment-system
spec:
  # Payment service का git repository
  url: https://github.com/razorpay/payment-gateway-gitops
  ref:
    branch: main
  interval: 30s # तुरंत changes detect करने के लिए
  secretRef:
    name: git-auth
  # Verify commits for security (payment system के लिए जरूरी)
  verify:
    mode: strict
    secretRef:
      name: flux-gpg-key

---
# Kustomization for Payment Production Environment
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: payment-production
  namespace: flux-payment-system
spec:
  interval: 5m # Production में regular sync
  sourceRef:
    kind: GitRepository
    name: payment-gateway-repo
  path: "./environments/production"
  prune: true
  timeout: 10m
  
  # Payment system के लिए health checks
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: payment-gateway
      namespace: payment-production
    - apiVersion: apps/v1
      kind: Deployment
      name: payment-processor
      namespace: payment-production
    - apiVersion: apps/v1
      kind: Deployment
      name: fraud-detection
      namespace: payment-production
  
  # Dependencies - database से पहले payment service deploy नहीं होगी
  dependsOn:
    - name: payment-database
    - name: payment-monitoring
  
  # Post deployment validations
  postBuild:
    substitute:
      ENVIRONMENT: "production"
      REGION: "mumbai"
      COMPLIANCE_MODE: "rbi-strict"
      MAX_TPS: "50000" # 50k transactions per second
      CURRENCY_SUPPORT: "INR,USD,EUR"

---
# HelmRepository for Payment Charts
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: payment-charts
  namespace: flux-payment-system
spec:
  url: https://charts.razorpay.com
  interval: 5m
  secretRef:
    name: helm-auth

---
# HelmRelease for Payment Gateway
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: razorpay-gateway
  namespace: flux-payment-system
spec:
  interval: 10m
  chart:
    spec:
      chart: payment-gateway
      version: "2.1.x"
      sourceRef:
        kind: HelmRepository
        name: payment-charts
        namespace: flux-payment-system
  
  # Indian payment system specific values
  values:
    replicaCount: 10 # High availability के लिए
    
    image:
      repository: razorpay/payment-gateway
      tag: "v2.1.5"
      pullPolicy: Always
    
    service:
      type: LoadBalancer
      port: 443
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-south-1:123456789012:certificate/razorpay-ssl"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    
    # Indian compliance requirements
    config:
      rbi_compliance: true
      pci_dss_level: "1"
      data_residency: "india"
      audit_logging: true
      encryption_at_rest: true
      encryption_in_transit: true
      
      # Payment methods supported in India
      payment_methods:
        - "upi"
        - "netbanking" 
        - "cards"
        - "wallets"
        - "emi"
        - "cardless_emi"
      
      # Indian banks integration
      bank_integrations:
        - "sbi"
        - "hdfc"
        - "icici"
        - "axis"
        - "kotak"
        - "yes_bank"
      
      # UPI handles
      upi_handles:
        - "razorpay@icici"
        - "razorpay@hdfc"
        - "razorpay@axis"
    
    # Resources for Indian traffic patterns
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    
    # Autoscaling for festival seasons (Diwali, etc.)
    autoscaling:
      enabled: true
      minReplicas: 10
      maxReplicas: 100
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    
    # Monitoring and observability
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          app: payment-gateway
          tier: production
      
      # Indian specific metrics
      customMetrics:
        - upi_transactions_per_second
        - failed_transactions_percentage
        - average_transaction_time_ms
        - festival_load_multiplier
        - rbi_compliance_score
    
    # Security configurations
    security:
      networkPolicy:
        enabled: true
        ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  name: payment-frontend
          - from:
            - namespaceSelector:
                matchLabels:
                  name: merchant-dashboard
      
      podSecurityPolicy:
        enabled: true
        runAsNonRoot: true
        readOnlyRootFilesystem: true
      
      # Secrets management
      vault:
        enabled: true
        role: "payment-gateway"
        secrets:
          - path: "secret/payment/database"
            key: "connection_string"
          - path: "secret/payment/encryption"
            key: "master_key"
          - path: "secret/payment/banks"
            key: "api_keys"

---
# Alert Manager for Payment System
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: payment-system-alerts
  namespace: flux-payment-system
spec:
  providerRef:
    name: slack-payment-alerts
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: payment-gateway-repo
    - kind: Kustomization
      name: payment-production
    - kind: HelmRelease
      name: razorpay-gateway
  summary: "Payment System GitOps Alert - {{ .Involved.kind }}/{{ .Involved.name }}"

---
# Slack Provider for Alerts
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack-payment-alerts
  namespace: flux-payment-system
spec:
  type: slack
  channel: "#payment-ops-alerts"
  secretRef:
    name: slack-webhook-secret

---
# Image Update Automation for Payment Gateway
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: payment-gateway-images
  namespace: flux-payment-system
spec:
  image: razorpay/payment-gateway
  interval: 1m # तुरंत new images detect करने के लिए
  secretRef:
    name: docker-registry-secret

---
# Image Policy for Automatic Updates
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: payment-gateway-policy
  namespace: flux-payment-system
spec:
  imageRepositoryRef:
    name: payment-gateway-images
  policy:
    semver:
      range: ">=2.1.0 <3.0.0" # Only patch और minor updates
  filterTags:
    pattern: '^v(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$'
    extract: '$major.$minor.$patch'

---
# Image Update Automation
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: payment-gateway-automation
  namespace: flux-payment-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: payment-gateway-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: gitops@razorpay.com
        name: Flux Payment Bot
      messageTemplate: |
        Automated payment gateway image update
        
        Updated payment-gateway from {{ .OldImage }} to {{ .NewImage }}
        
        Automation: {{ .AutomationObject }}
        
        Files updated:
        {{ range .Updated.Files -}}
        - {{ . }}
        {{ end -}}
    push:
      branch: main
  update:
    path: "./environments/production"
    strategy: Setters